[package]
name = "xfs_dev_mgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
winapi = { version = "0.3", features = ["everything"] }

[[bin]]
name = "xfs_dev_mgr"
